/**
 * Playwright E2E tests for Password Reset Flow (US-004)
 * 
 * User journey:
 * 1. User clicks "Forgot Password" on login page
 * 2. User enters email and submits
 * 3. User sees success message (regardless of email validity)
 * 4. User clicks reset link (retrieved via test hook)
 * 5. User enters new password and confirms
 * 6. User redirected to login with success message
 * 7. User logs in with new password successfully
 * 
 * Edge cases:
 * - Expired token shows error with link to request new reset
 * - Mismatched password confirmation shows error
 */

import { test, expect } from '@playwright/test';

test.describe('E2E Password Reset Flow', () => {
  const testEmail = 'passwordreset@example.com';
  const oldPassword = 'OldStr0ng!Pass';
  const newPassword = 'NewStr0ng!Pass';

  test.beforeEach(async ({ page }) => {
    // Assume user already exists with oldPassword
    // In real tests, this would be set up via API or DB seed
  });

  test('Complete password reset flow: forgot → reset → login', async ({ page }) => {
    // Step 1: Go to login page and click "Forgot Password"
    await page.goto('http://localhost:3000/login');
    await page.click('a[href="/auth/forgot-password"]');
    
    expect(page.url()).toContain('/forgot-password');

    // Step 2: Enter email and submit
    await page.fill('input[name="email"]', testEmail);
    await page.click('button[type="submit"]');

    // Step 3: See success message
    await expect(page.locator('h2.text-2xl.font-bold')).toContainText(/Check Your Email/i, { timeout: 5000 });

    // Step 4: Get reset token from test hook
    const tokenResp = await page.request.get('http://localhost:3001/test-hooks/last-reset-token');
    expect(tokenResp.status()).toBe(200);
    const body = await tokenResp.json();
    const resetToken = body.token;

    // Step 5: Navigate to reset password page with token
    await page.goto(`http://localhost:3000/auth/reset-password?token=${resetToken}`);

    // Step 6: Enter and confirm new password
    await page.fill('input[name="password"]', newPassword);
    await page.fill('input[name="confirmPassword"]', newPassword);
    await page.click('button[type="submit"]');

    // Step 7: Redirected to login
    await expect(page).toHaveURL(/\/login/, { timeout: 5000 });

    // Step 8: Login with new password
    await page.fill('input[name="email"]', testEmail);
    await page.fill('input[name="password"]', newPassword);
    await page.click('button[type="submit"]');

    // Step 9: Successfully logged in
    await expect(page).toHaveURL(/\/dashboard/);
  });

  test('Forgot password form validation', async ({ page }) => {
    await page.goto('http://localhost:3000/auth/forgot-password');

    // Submit invalid email
    await page.fill('input[name="email"]', 'not-an-email');
    await page.click('button[type="submit"]');
    await expect(page.locator('div.bg-red-100.border-red-400.text-red-700'))
      .toContainText(/valid email/i, { timeout: 3000 });
  });

  test('Reset password form validation', async ({ page }) => {
    // Get a valid token first
    await page.goto('http://localhost:3000/auth/forgot-password');
    await page.fill('input[name="email"]', testEmail);
    await page.click('button[type="submit"]');

    const tokenResp = await page.request.get('http://localhost:3001/test-hooks/last-reset-token');
    const body = await tokenResp.json();
    const resetToken = body.token;

    await page.goto(`http://localhost:3000/auth/reset-password?token=${resetToken}`);

    // Test weak password (< 8 chars)
    await page.fill('input[name="password"]', 'weak');
    await page.fill('input[name="confirmPassword"]', 'weak');
    await page.click('button[type="submit"]');
    await expect(page.locator('div.bg-red-100.border-red-400.text-red-700'))
      .toContainText(/8 characters/i, { timeout: 3000 });

    // Test mismatched passwords
    await page.fill('input[name="password"]', newPassword);
    await page.fill('input[name="confirmPassword"]', 'DifferentPass123!');
    await page.click('button[type="submit"]');
    await expect(page.locator('div.bg-red-100.border-red-400.text-red-700'))
      .toContainText(/passwords.*match/i, { timeout: 3000 });
  });

  test('Expired token shows error with link to request new reset', async ({ page }) => {
    // Use expired token (this would be generated by test hook with past expiry)
    const expiredToken = 'expired.test.token';
    
    await page.goto(`http://localhost:3000/auth/reset-password?token=${expiredToken}`);
    await page.fill('input[name="password"]', newPassword);
    await page.fill('input[name="confirmPassword"]', newPassword);
    await page.click('button[type="submit"]');

    // Should show expiry error
    await expect(page.locator('div.bg-red-100.border-red-400.text-red-700'))
      .toContainText(/token.*expired|link.*expired|invalid/i, { timeout: 3000 });

    // Should have link to request new reset
    const resetLink = page.locator('a[href="/auth/forgot-password"]');
    await expect(resetLink).toBeVisible();
  });

  test('Invalid token shows error', async ({ page }) => {
    await page.goto('http://localhost:3000/auth/reset-password?token=invalid.token.here');
    await page.fill('input[name="password"]', newPassword);
    await page.fill('input[name="confirmPassword"]', newPassword);
    await page.click('button[type="submit"]');

    await expect(page.locator('div.bg-red-100.border-red-400.text-red-700'))
      .toContainText(/invalid.*token|link.*invalid|expired/i, { timeout: 3000 });
  });

  test('Used token shows error', async ({ page }) => {
    // Get valid token
    await page.goto('http://localhost:3000/auth/forgot-password');
    await page.fill('input[name="email"]', testEmail);
    await page.click('button[type="submit"]');

    const tokenResp = await page.request.get('http://localhost:3001/test-hooks/last-reset-token');
    const body = await tokenResp.json();
    const resetToken = body.token;

    // Use token once
    await page.goto(`http://localhost:3000/auth/reset-password?token=${resetToken}`);
    await page.fill('input[name="password"]', newPassword);
    await page.fill('input[name="confirmPassword"]', newPassword);
    await page.click('button[type="submit"]');
    await expect(page).toHaveURL(/\/login/, { timeout: 5000 });

    // Try to use token again
    await page.goto(`http://localhost:3000/auth/reset-password?token=${resetToken}`);
    await page.fill('input[name="password"]', 'AnotherPass123!');
    await page.fill('input[name="confirmPassword"]', 'AnotherPass123!');
    await page.click('button[type="submit"]');

    await expect(page.locator('div.bg-red-100.border-red-400.text-red-700'))
      .toContainText(/already.*used|token.*used|invalid|expired/i, { timeout: 3000 });
  });

  test('Second forgot-password request works (invalidates first)', async ({ page }) => {
    // First request
    await page.goto('http://localhost:3000/auth/forgot-password');
    await page.fill('input[name="email"]', testEmail);
    await page.click('button[type="submit"]');

    let tokenResp = await page.request.get('http://localhost:3001/test-hooks/last-reset-token');
    let body = await tokenResp.json();
    const firstToken = body.token;

    // Second request (invalidates first)
    await page.goto('http://localhost:3000/auth/forgot-password');
    await page.fill('input[name="email"]', testEmail);
    await page.click('button[type="submit"]');

    tokenResp = await page.request.get('http://localhost:3001/test-hooks/last-reset-token');
    body = await tokenResp.json();
    const secondToken = body.token;

    expect(firstToken).not.toBe(secondToken);

    // First token should now be invalid
    await page.goto(`http://localhost:3000/auth/reset-password?token=${firstToken}`);
    await page.fill('input[name="password"]', newPassword);
    await page.fill('input[name="confirmPassword"]', newPassword);
    await page.click('button[type="submit"]');

    await expect(page.locator('div.bg-red-100.border-red-400.text-red-700'))
      .toContainText(/invalid.*token|token.*expired/i, { timeout: 3000 });

    // Second token should work
    await page.goto(`http://localhost:3000/auth/reset-password?token=${secondToken}`);
    await page.fill('input[name="password"]', newPassword);
    await page.fill('input[name="confirmPassword"]', newPassword);
    await page.click('button[type="submit"]');

    await expect(page).toHaveURL(/\/login/, { timeout: 5000 });
  });
});
